// Do not edit. This file is machine generated by the Resource DLL Wizard.

library ARMHR;

{ITE} {DFMFileType} {BGunit.dfm}
{ITE} {DFMFileType} {ConnectUnit.dfm}
{ITE} {DFMFileType} {MainUnit.dfm}
{ITE} {RCFileType} {Win32\Debug\ARMHR_DRC.rc}

{$R 'BGunit.dfm' 'BackData:TDataModule'}
{$R 'ConnectUnit.dfm' 'ConnectForm:TForm'}
{$R 'MainUnit.dfm' 'MainForm:TForm'}
{$R 'Win32\Debug\ARMHR_DRC.res' 'Win32\Debug\ARMHR_DRC.rc'}

{$E ENU}

begin
end.
